rgname                 = "stage-chimdi-rg"
service_principal_name = "stage-chimdi-spn"
keyvault_name          = "stage-chimdi-kv-101"
SUB_ID = ""
node_pool_name = "stagenp"
cluster_name = "stage-chimdi-cluster"
