trigger: none

parameters:
- name: environment
  type: string
  values:
  - dev
  - staging
  - prod
  default: dev


stages:
  - stage: plan_destroy
    jobs:
      - job: terraform_plan_destroy
        pool:
         vmImage: 'ubuntu-latest'
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/lessons/day26/${{parameters.environment}}'
              backendAzureRmUseEntraIdForAuthentication: false
              backendServiceArm: 'Azure subscription 1(82484a7b-d6c1-47cd-9121-62f0609fcef2)'
              backendAzureRmResourceGroupName: 'terraform-state-rg'
              backendAzureRmStorageAccountName: 'tf${{parameters.environment}}backend2026chimdi'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: '${{parameters.environment}}.state'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/lessons/day26/${{parameters.environment}}'
              environmentServiceNameAzureRM: 'Azure subscription 1(82484a7b-d6c1-47cd-9121-62f0609fcef2)'         

  - stage: destroy
    jobs:
      - job: destroy
        pool:
         vmImage: 'ubuntu-latest'
        steps:
            - task: TerraformInstaller@1
              inputs:
                terraformVersion: 'latest'
            - task: TerraformTask@5
              inputs:
                provider: 'azurerm'
                command: 'init'
                workingDirectory: '$(System.DefaultWorkingDirectory)/lessons/day26/${{parameters.environment}}'
                backendAzureRmUseEntraIdForAuthentication: false
                backendServiceArm: 'Azure subscription 1(82484a7b-d6c1-47cd-9121-62f0609fcef2)'
                backendAzureRmResourceGroupName: 'terraform-state-rg'
                backendAzureRmStorageAccountName: 'tf${{parameters.environment}}backend2026chimdi'
                backendAzureRmContainerName: 'tfstate'
                backendAzureRmKey: '${{parameters.environment}}.state'
            - task: TerraformTask@5
              inputs:
                provider: 'azurerm'
                command: 'destroy'
                workingDirectory: '$(System.DefaultWorkingDirectory)/lessons/day26/${{parameters.environment}}'
                commandOptions: '--auto-approve'
                environmentServiceNameAzureRM: 'Azure subscription 1(82484a7b-d6c1-47cd-9121-62f0609fcef2)'

           
